# Fire-age colour ramps, and the checks that validated them.
#
# Sourcing this file only defines the ramps and the helpers -- it prints nothing
# and computes nothing expensive. Call validate_ramps() to re-run the report, or
# build_ramps() to regenerate the hexes from scratch.
#
# The ramps below were generated by build_ramps() and are pasted in as constants
# deliberately: hand-picked hexes are the thing the method forbids, but
# re-deriving them by numerical search on every source() is slow, and it makes the
# committed colours depend on a search converging identically every time.
#
# Each ramp is ordered OLDEST burn -> NEWEST burn.

# ---- the validated ramps -----------------------------------------------------

fire_ramps <- list(
  # Warm heat ramp, deep ember -> gold. Reads unambiguously as fire.
  ember = c("#931815", "#AF441A", "#CA6A24", "#E58F2E", "#FAB74A", "#FCE2A3"),

  # Crimson -> gold. Best era separation of the four on the real map: old burns
  # read distinctly crimson against recent gold. This is the one in use.
  crimson = c("#8C1754", "#C12347", "#E94D24", "#F6892F", "#FABD65", "#FDEBA9"),

  # Single-hue orange: the strictly compliant "one hue, light -> dark" option.
  # Flattest of the four; kept as the conservative fallback.
  orange1 = c("#763F11", "#985219", "#BA6621", "#DE7B29", "#F89850", "#FABF98"),

  # Violet -> gold, the magma/inferno family with the dark end lifted clear of
  # the background. Strongest separation, but the violet stops reading as fire.
  violet_gold = c("#741994", "#B5228A", "#F32F67", "#F8855E", "#FABC7A", "#FDEBA9")
)

# Map background these ramps were validated against. Darker than the #1a1a19
# chart surface on purpose: pushing the background AWAY from the ramp's dark end
# is what lets 40-year-old burns clear the 2:1 contrast gate.
fire_surface <- "#0d0d0d"

# ---- colour space ------------------------------------------------------------

srgb_to_linear <- function(c) ifelse(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055)^2.4)
linear_to_srgb <- function(c) ifelse(c <= 0.0031308, c * 12.92, 1.055 * c^(1 / 2.4) - 0.055)

hex_to_oklab <- function(hex) {
  lin <- srgb_to_linear(t(grDevices::col2rgb(hex)) / 255)
  l <- 0.4122214708 * lin[, 1] + 0.5363325363 * lin[, 2] + 0.0514459929 * lin[, 3]
  m <- 0.2119034982 * lin[, 1] + 0.6806995451 * lin[, 2] + 0.1073969566 * lin[, 3]
  s <- 0.0883024619 * lin[, 1] + 0.2817188376 * lin[, 2] + 0.6299787005 * lin[, 3]
  l_ <- l^(1 / 3); m_ <- m^(1 / 3); s_ <- s^(1 / 3)
  cbind(L = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        b = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_)
}

oklch <- function(hex) {
  lab <- hex_to_oklab(hex)
  data.frame(hex = hex, L = lab[, "L"],
             C = sqrt(lab[, "a"]^2 + lab[, "b"]^2),
             h = (atan2(lab[, "b"], lab[, "a"]) * 180 / pi) %% 360)
}

luminance <- function(hex) {
  lin <- srgb_to_linear(t(grDevices::col2rgb(hex)) / 255)
  0.2126 * lin[, 1] + 0.7152 * lin[, 2] + 0.0722 * lin[, 3]
}

contrast <- function(a, b) {
  la <- luminance(a); lb <- luminance(b)
  (pmax(la, lb) + 0.05) / (pmin(la, lb) + 0.05)
}

dE <- function(h1, h2) {
  sqrt(rowSums((hex_to_oklab(h1) - hex_to_oklab(h2))^2)) * 100
}

# ---- validation --------------------------------------------------------------

# The reference JS validator needs node, which is not installed here, so the
# ordinal-ramp checks are implemented directly:
#   - monotone OKLCH lightness
#   - adjacent delta-L >= 0.06
#   - darkest step clears 2:1 against the map background
#   - hue span reported (a "semantic heat" ramp is the documented multi-hue
#     sequential exception, and obliges a scale legend)
#
# Plus one check the generic validator cannot know to make: a fire scar is drawn
# ON hillshaded terrain, so it must also separate from NEUTRAL GREY. Against grey
# of equal lightness, OKLab distance reduces exactly to chroma x 100, so this is
# a chroma floor -- without it, a desaturated ramp end passes every lightness
# gate and still vanishes into the terrain.
check_ramp <- function(name, ramp, surface = fire_surface, verbose = TRUE) {
  if (!requireNamespace("colorspace", quietly = TRUE)) {
    stop("colorspace is needed for the CVD simulation")
  }
  m <- oklch(ramp); k <- length(ramp)
  dL <- diff(m$L)
  con <- contrast(ramp, surface)
  hspan <- diff(range(((m$h - m$h[1] + 180) %% 360) - 180))
  grey_dE <- m$C * 100

  # Machado, Oliveira & Fernandes (2009) at severity 1.0 -- the model the
  # standard names, which is what colorspace implements.
  cvd <- min(
    dE(colorspace::protan(ramp[-k], severity = 1),
       colorspace::protan(ramp[-1], severity = 1)),
    dE(colorspace::deutan(ramp[-k], severity = 1),
       colorspace::deutan(ramp[-1], severity = 1)))

  res <- list(name = name, ramp = ramp,
              monotone = all(dL > 0), min_dL = min(dL),
              dark_contrast = min(con), hue_span = hspan,
              min_grey_dE = min(grey_dE), worst_cvd = cvd)
  res$pass <- res$monotone && res$min_dL >= 0.06 &&
    res$dark_contrast >= 2 && res$min_grey_dE >= 8

  if (verbose) {
    cat("\n===== ", name, " =====\n", sep = "")
    print(data.frame(hex = m$hex, L = round(m$L, 3), C = round(m$C, 3),
                     h = round(m$h), vs_surface = round(con, 2),
                     vs_grey_dE = round(grey_dE, 1)), row.names = FALSE)
    cat(sprintf("  monotone L            : %s\n", ifelse(res$monotone, "PASS", "FAIL")))
    cat(sprintf("  min adjacent dL >=0.06: %.3f  %s\n", res$min_dL,
                ifelse(res$min_dL >= 0.06, "PASS", "FAIL")))
    cat(sprintf("  darkest vs surface>=2 : %.2f:1  %s\n", res$dark_contrast,
                ifelse(res$dark_contrast >= 2, "PASS", "FAIL")))
    cat(sprintf("  min dE vs grey    >=8 : %.1f  %s\n", res$min_grey_dE,
                ifelse(res$min_grey_dE >= 8, "PASS", "FAIL")))
    cat(sprintf("  hue span              : %.0f deg (%s)\n", hspan,
                ifelse(hspan <= 30, "single-hue",
                       "semantic heat; needs scale legend")))
    cat(sprintf("  worst adjacent CVD dE : %.1f\n", res$worst_cvd))
  }
  invisible(res)
}

validate_ramps <- function(ramps = fire_ramps, surface = fire_surface) {
  res <- lapply(names(ramps), function(n) check_ramp(n, ramps[[n]], surface))
  cat("\n\n===== SUMMARY (background ", surface, ") =====\n", sep = "")
  print(data.frame(
    ramp       = vapply(res, function(r) r$name, character(1)),
    monotone   = vapply(res, function(r) r$monotone, logical(1)),
    min_dL     = round(vapply(res, function(r) r$min_dL, numeric(1)), 3),
    vs_surface = round(vapply(res, function(r) r$dark_contrast, numeric(1)), 2),
    vs_grey    = round(vapply(res, function(r) r$min_grey_dE, numeric(1)), 1),
    hue_span   = round(vapply(res, function(r) r$hue_span, numeric(1))),
    worst_cvd  = round(vapply(res, function(r) r$worst_cvd, numeric(1)), 1),
    overall    = ifelse(vapply(res, function(r) r$pass, logical(1)),
                        "PASS", "FAIL")), row.names = FALSE)
  invisible(res)
}

# ---- regeneration ------------------------------------------------------------
# Only needed to derive a new ramp; not run on source().

oklch_to_linrgb <- function(L, C, h) {
  hr <- h * pi / 180
  a <- C * cos(hr); b <- C * sin(hr)
  l_ <- L + 0.3963377774 * a + 0.2158037573 * b
  m_ <- L - 0.1055613458 * a - 0.0638541728 * b
  s_ <- L - 0.0894841775 * a - 1.2914855480 * b
  l <- l_^3; m <- m_^3; s <- s_^3
  cbind(r =  4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        b = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s)
}

in_gamut <- function(L, C, h, tol = 1e-4) {
  v <- oklch_to_linrgb(L, C, h)
  all(v >= -tol & v <= 1 + tol)
}

max_chroma <- function(L, h, hi = 0.45) {
  lo <- 0
  if (in_gamut(L, hi, h)) return(hi)
  for (i in 1:40) {
    mid <- (lo + hi) / 2
    if (in_gamut(L, mid, h)) lo <- mid else hi <- mid
  }
  lo
}

oklch_to_hex <- function(L, C, h) {
  v <- pmin(pmax(oklch_to_linrgb(L, C, h), 0), 1)
  s <- linear_to_srgb(v)
  grDevices::rgb(s[, 1], s[, 2], s[, 3])
}

# Smallest lightness at this hue whose max-chroma colour still clears `target`
# contrast against the background. This is what sets the ramp's dark end, and
# every hand-picked ramp failed it.
min_L_for_contrast <- function(h, surface = fire_surface, target = 2.2,
                               chroma_frac = 0.9) {
  f <- function(L) {
    contrast(oklch_to_hex(L, chroma_frac * max_chroma(L, h), h), surface) - target
  }
  if (f(0.05) > 0) return(0.05)
  stats::uniroot(f, c(0.05, 0.95), tol = 1e-4)$root
}

# h_to may exceed 360 to force the sweep direction: the hue wheel is circular, so
# seq(355, 95) descends through blue and green and yields a rainbow. Write the
# target as 455 to sweep the warm way (magenta -> red -> orange -> gold).
make_ramp <- function(n, L_from, L_to, h_from, h_to, chroma_frac = 0.9) {
  L <- seq(L_from, L_to, length.out = n)
  h <- seq(h_from, h_to, length.out = n) %% 360
  vapply(seq_len(n), function(i) {
    oklch_to_hex(L[i], chroma_frac * max_chroma(L[i], h[i]), h[i])
  }, character(1))
}

build_ramps <- function(n = 6, surface = fire_surface) {
  L_lo <- max(vapply(c(30, 45, 55), min_L_for_contrast, numeric(1),
                     surface = surface))
  list(ember       = make_ramp(n, L_lo, 0.92, 28, 88),
       crimson     = make_ramp(n, L_lo, 0.94, 355, 455),
       orange1     = make_ramp(n, L_lo, 0.85, 55, 55),
       violet_gold = make_ramp(n, L_lo, 0.94, 315, 455))
}
